on:
  workflow_dispatch:
  push:
    branches:
      - main
    pull_request:

jobs:
  build:
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
      - name: cd into daemon
      - run: cd cmd/tomad 
      
      - name build daemon
      - run: go install -tags ledger ./...

      - name: build node
      - run: sudo apt-get install make && cd ../.. && sudo make install
